### ISSUE TITLE
Stealing focus

### ISSUE THREAD

**Issue by lzap** [knopwob/dunst#195]
Hello,

I noticed that version in Fedora 20 (dunst-1.0.0-2.fc20.x86_64) now steals my focus when a message appears. I use i3wm and it is possible there was a change in i3wm recently. This is annoying.

Do you happen to know what can be possibly wrong? Thanks!

**Comment by hughdavenport** [comment]
Hi @lzap,

Is this still an issue for you on the latest dunst?

Cheers,

Hugh

**Comment by lzap** [comment]
Oh no, an update had to fix this! (I am still on F20 fy)

```
[lzap@lzapx ~]$ rpm -q dunst i3
dunst-1.1.0-2.fc21.x86_64
i3-4.9.1-1.fc21.x86_64
```

**Comment by lzap** [comment]
Oops I mean I am on F21 :) Time files.
