### ISSUE TITLE
Script does not execute with format=""

### ISSUE THREAD

**Issue by phealy** [knopwob/dunst#212]
I am using Spotify on Linux with i3, and have my currently playing song display in my i3bar. I want to do the following two things on a notification from Spotify:
1) Fire a script to tell i3blocks to update the currently playing song
2) Suppress the notification (with format=""?)

If I set format="", the script never fires; without format="" the script works great but I get a notification I don't want to see.

I've confirmed that this still occurs in git as of today. Is there a way to do this?

**Comment by hughdavenport** [comment]
Hi,

I'm a bit confused on how you are going about what you want to achieve here. Would you be able to post your scripts you are using?

Cheers,

Hugh

**Comment by springworm** [comment]
Hi phealy --
I actually patched this feature into dunst months ago for the same reason as you. I wasn't sure if I should bother putting it out, but I guess there are users in need of this feature! Hopefully the feature can be merged in.
