### ISSUE TITLE
Action

### ISSUE THREAD

**Issue by Vladimir-csp** [knopwob/dunst#220]
Hi!
I'm using dunst 1.1.0, and I can not use actions or URLs.
I've bound context = mod4+Insert.
When a notification with action or URL appears, the keybinding just silently does nothing.
Console output:
```
$ dunst
no locale support

(process:32269): GLib-CRITICAL **: g_variant_unref: assertion 'value->ref_count > 0' failed
```
I'm positive that keybinding is sent to dunst.

**Comment by hughdavenport** [comment]
Hi,

Do you have the dmenu option set? Does it have a valid path (can you run it manually)? Would you have any other applications (xbindkeys/window manager/etc) that may have that key combination?
FWIW, my context is `ctrl+shift+period`, and dmenu is `/usr/bin/dmenu -p dunst:`, and I can get context menu for URL's

Does the error you posted above happen before/during/after the notification with an action/URL?

Cheers,

Hugh

**Comment by Vladimir-csp** [comment]
It slipped my attention that dmenu was needed for that. Thanks!

**Comment by drzraf** [comment]
Unless I overlooked something, there is no documentation about how "actions" are expect to work. Can a notification transmit a "accept" / "cancel" value, and how. How is dmenu integration expected to be done? Does it works out of the box in absence of previous configuration?

Worth mentioning:
https://github.com/blueman-project/blueman/issues/68
