### ISSUE TITLE
multiple instances of dunst - hotkeys working only in one instance

### ISSUE THREAD

**Issue by petr-fischer** [knopwob/dunst#244]
Hello there - I have problems with 2 instances of dunst running (under same user). If second instance occur, second instance notification overlap first instance notifications and hotkeys for closing notifications works only for the first instance (most likely).

I have some scripts, running from cron (cronie, arch linux) - this cron-jobs emits notifications via notify-send (DISPLAY=:0 is needed for displaying notifications from cron scripts) - is this a problem? 

Thanks very much.

**Comment by Narrat** [comment]
Is this for the user crontab or the root one?

**Comment by petr-fischer** [comment]
This is user crontabs (with X11 running). 

More details (findings):

This is from pstree (tree of processes):
1)
systemd(1)---systemd(1518)---dunst(1536)-+-{gdbus}(1536)
                                         `-{gmain}(1536)
2)
systemd(1)---dunst(2813)-+-{gdbus}(2813)
                         |-{gmain}(2813)
                         `-{pool}(2813)

Findings:

This is no problem scenario:
1) first dunst process shows a notification (user cron)
2) I close it with hotkey
3) second dunst process shows a notification (xterm)
4) I close it with hotkey
No problem at all.

This is PROBLEMATIC scenario:
1) first dunst process shows a notification
2) (no action from me, first notification still on the screen)
3) second dunst process shows a notification (the first notification gone from screen!!!)
Now I cant close the one remaining notification by hotkey and this problem persist for the one running dunst process.

So the problem is only in scenario, where both of dunst processes had some notifications on the screen simultaneously - from this moment, hotkeys for one of the processes are broken.

Is it clear?

**Comment by Narrat** [comment]
How do you start your desktop (Which DisplayManager, or just plain startx (if so, how does the xinitrc look like?))
Do your scripts, that will be run from cron, source the DBUS_SESSION_BUS_ADDRESS?

**Comment by petr-fischer** [comment]
LightDM started after boot as systemd service, then i3wm.

I am setting only DISPLAY=:0 in the cron scripts, but DBUS_SESSION_BUS_ADDRESS is news to me.

**Comment by Narrat** [comment]
Ok, if using LightDM, the session should have a running dbus

At least in the past, sourcing the DBUS_SESSION_BUS_ADDRESS was needed to achieve working notifications, as cron didn't get that env. Could be a source for your problem

**Comment by petr-fischer** [comment]
Solved.

In user cron environment, there is not DBUS_SESSION_BUS_ADDRESS. So this is the solution:

1) save DBUS_SESSION_BUS_ADDRESS to a file after X11 session start (in i3wm config):
echo $DBUS_SESSION_BUS_ADDRESS > ~/.cache/dbusaddr

2) the in cron script, read value from file and store in varibale:
export DBUS_SESSION_BUS_ADDRESS=`cat ~/.cache/dbusaddr`

I don't know better solution, but notifications now works perfectly.
Thanks very much for your assistence Narrat! Very helpfull.

**Comment by blueyed** [comment]
JFI: In some script I've used the following for `gnome-session`: `export DBUS_SESSION_BUS_ADDRESS="$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/${pid_gnome_session}/environ|cut -d= -f2-)"`.
