### ISSUE TITLE
dunst with multiple X DISPLAYs / DBUS setup

### ISSUE THREAD

**Issue by blueyed** [knopwob/dunst#247]
I am using two window manager sessions in parallel on different X DISPLAYs.

I have a global DBUS session for the user (with Arch Linux), and dunst (or rather the org.freedesktop.Notifications D-BUS Service) seems to be global across the different X sessions then.

Would it be possible to notify a running dunst about a changed DISPLAY value - in case you wanted to have notifications globally (which might not be the case anyway)?

I can update the DBUS environment with `dbus-update-activation-environment --systemd DISPLAY XAUTHORITY`, but that only affects dunst when it's started - not during runtime.

Another solution would be using `dbus-launch` to have a separate DBUS session per X DISPLAY.

Given https://wiki.archlinux.org/index.php/Systemd/User#D-Bus and https://www.archlinux.org/news/d-bus-now-launches-user-buses/ I am not sure if manually using `dbus-launch` is the right way to do.

It is similar to `gpg-agent`, where `echo UPDATESTARTUPTTY | gpg-connect-agent` is needed to make pinentry dialogs show up on the correct display.

**Comment by mathstuf** [comment]
You might want a repeater to send notifications between the two X sessions (there are numerous D-Bus watchers that could probably be used for this). This seems very niche to me, but would require quite a bit of code from dunst, but still not work for other D-Bus services (password prompts, bluetooth agents, etc.).

**Comment by blueyed** [comment]
> there are numerous D-Bus watchers that could probably be used for this

Can you recommend something?

I am using a separate D-Bus session per X session by now, so the issue is not really relevant anymore - especially given your feedback.  Thanks!

**Comment by mathstuf** [comment]
There's `dbus-monitor` that I use for debugging. There's also `dfeet`, but that may be a GUI thing (from GNOME). There's also `qdbus`, but I don't know if it does monitoring.
