### ISSUE TITLE
Allow hiding of notifications without ignoring them.

### ISSUE THREAD

**Issue by thwischm** [knopwob/dunst#249]
I was trying to get the album art for a song to display as the icon in Spotify notifications. I have a working script for this thats executed using the script option in dunst and then uses notify-send to send another notification with the album art. The problem is that the original notification sent by Spotify still shows up. I thought it wouldn't be a problem to hide it using format="", but that just ignores the notification completely and doesn't start the script. 
I'm probably just doing this wrong and there's a better way to get notifications from Spotify, but i still think being able to modify the content of notifications using scripts would be a nice feature.

**Comment by thwischm** [comment]
Nevermind, i just learned about the always_run_script option. So this is actually already possible.

**Comment by monkeynaleo** [comment]
Could you post your script?? @thwischm

**Comment by thwischm** [comment]
No need. The feature I was suggesting already exists and I got it working. I just didn't know where to look and eventually found always_run_script in a random reddit thread. This can be closed.

**Comment by thwischm** [comment]
Oh, I can actually do that myself. Sorry, I'm pretty new to this stuff.

**Comment by monkeynaleo** [comment]
what do you have in your script that resends the notification with album art? @thwischm

**Comment by thwischm** [comment]
Here's my script:

     #!/bin/sh
     
     cover_location="/tmp/spotify-cover"
     dunstify_id="/tmp/spotify-notify_dunstify_id"
     
     title=$2
     body=$3
     artist=$(echo "$body" | sed -e 's/ - .*//' -e 's/\s/%20/g')
     album=$(echo "$body" | sed -e 's/.* - //' -e 's/\s/%20/g')
     
     # echo "https://api.spotify.com/v1/search?q=$album%20$artist&type=album"
     # echo $(curl -X GET "https://api.spotify.com/v1/search?q=$album%20$artist&type=album")
     
     url=$(curl -X GET "https://api.spotify.com/v1/search?q=$album%20$artist&type=album" | jq -r'.albums.items[0].images[-1].url')
     
     curl -o $cover_location $url
     
     convert $cover_location -resize 50% "${cover_location}.png"
     
     [ ! -z "$(cat "$dunstify_id")" ] && id_arg="-r $(cat "$dunstify_id")"
     
     dunstify \
       -a "ncmpcpp" \
       -i "${cover_location}.png" \
       "$title" \
      "$body" \
      -p $id_arg > "$dunstify_id"
