### ISSUE TITLE
Is it possible to play a sound when a notification pops up?

### ISSUE THREAD

**Issue by krompus** [knopwob/dunst#257]
Only the first time they are displayed, preferably (not when browsing history).

**Comment by Adaephon-GH** [comment]
Yes, it is possible by utilizing the scripting feature of the custom overrides.

First, you need some program or script that plays the sound. This script should either ignore all command line arguments or be able to act on those passed by `dunst` (e.g. `play_beep_sound.sh`, but not `play_sound /path/to/beep.wav`).  I use a simple shell script named `alert.sh` (remember to make it executable) for that:

    #!/bin/sh
    paplay /path/to/alert.wav

Then you need to configure a custom section in your `dunstrc`. If you want to play a sound on any notification, this should do:

    [play_sound]
        summary = "*"
        script = /path/to/alert.sh

After restarting `dunst` (If it starts automatically, just terminating the running instance should do), it will call the script `/path/to/alert.sh` every time a notification summary matches the pattern `*`. As `dunst` utilized shell-like globbing this means any summary and therefore every notification.

---

For more information and examples, please have a look at the [example `dunstrc`](https://github.com/knopwob/dunst/blob/master/dunstrc).

**Comment by krompus** [comment]
Awesome! Thank you so much!

I've assigned it to the text sound from Link to the Past, by the way. :)

https://soundgasm.net/u/krompus/LTTP_Text_Donewav

**Comment by rmonicovia** [comment]
2021, reached this page looking for a plane announcement sound to play with dunst notifications :-)

**Comment by krompus** [comment]
✈️

**Comment by stiliajohny** [comment]
> play_sound

is there a way to define what sound for what type of alerts ( low, critical etc ) ? 

TIA

**Comment by chu4ng** [comment]
@stiliajohny 
```
[urgency_low]
    script /path/to/sound1.sh
[urgency_critical]
    script /path/to/sound2.sh
```

**Comment by greeid** [comment]
> There are application which play their own sound for their notifications, for example outlook. Is it possible to exclude sound playing for those applications? More precisely, how can a rule be inverted?

Same question here, looking for a way to exclude Discord and spotify from notification sounds

**Comment by DeepReef11** [comment]
As explained in dunstrc, use the proper matching tag and change it's argument according to your need.

```
# Messages can be matched by
#    appname (discouraged, see desktop_entry)
#    body
#    category
#    desktop_entry
#    icon
#    match_transient
#    msg_urgency
#    stack_tag
#    summary
#
```

Summary is the title of the notification, body is the message, etc.

Don't forget to give execution permission to the alert.sh script: `sudo chmod +x alert.sh`.

**Comment by apoorv569** [comment]
> Yes, it is possible by utilizing the scripting feature of the custom overrides.
> 
> First, you need some program or script that plays the sound. This script should either ignore all command line arguments or be able to act on those passed by `dunst` (e.g. `play_beep_sound.sh`, but not `play_sound /path/to/beep.wav`). I use a simple shell script named `alert.sh` (remember to make it executable) for that:
> 
> ```
> #!/bin/sh
> paplay /path/to/alert.wav
> ```
> 
> Then you need to configure a custom section in your `dunstrc`. If you want to play a sound on any notification, this should do:
> 
> ```
> [play_sound]
>     summary = "*"
>     script = /path/to/alert.sh
> ```
> 
> After restarting `dunst` (If it starts automatically, just terminating the running instance should do), it will call the script `/path/to/alert.sh` every time a notification summary matches the pattern `*`. As `dunst` utilized shell-like globbing this means any summary and therefore every notification.
> 
> For more information and examples, please have a look at the [example `dunstrc`](https://github.com/knopwob/dunst/blob/master/dunstrc).

Is is possible to configure different sound if the body or level of notification is different?

I tried,
```
[play_sound]
    summary = "*"
    script = "/home/apoorv/.local/bin/scripts/general-notify-sound"

[play_sound]
    body = "^Battery low"
    script = "/home/apoorv/.local/bin/scripts/low-batt-notify-sound"
```

tried this as well,
```
[play_sound]
    summary = "*"
    script = "/home/apoorv/.local/bin/scripts/general-notify-sound"
    body = "^Battery low"
    script = "/home/apoorv/.local/bin/scripts/low-batt-notify-sound"
```

but in either case neither of the sound plays.. I can only have one,
```
[play_sound]
    summary = "*"
    script = "/home/apoorv/.local/bin/scripts/general-notify-sound"
```

How do I filter for different body or level? Also I use `dunst` for volume and brightness as well I don't want any sound on at least the brightness one.

**Comment by apoorv569** [comment]
> Just in case anyone finds it useful, the workaround I found to work better is to add the logic into the notification script itself. The attributes of the notification are available to the script via `DUNST_*` environment variables.
> 
> Ref: https://dunst-project.org/documentation/#SCRIPTING

Oh! Interesting.

Would you say this logic is correct (using `^` and all)?
```bash
#!/usr/bin/env bash

if [ "$DUNST_BODY" != "^Volume" ] && [ "$DUNST_BODY" != "^Brightness" ]; then
    pw-play ~/.local/share/sounds/notify1.ogg
elif [ "$DUNST_BODY" = "^Battery low" ]; then
    pw-play ~/.local/share/sounds/low_batt.ogg
elif [ "$DUNST_URGENCY" = "critical" ]; then
    pw-play ~/.local/share/sounds/notify2.ogg
fi
```

**Comment by asfaltboy** [comment]
I think that's almost right.

You used `^`, which seems like a regular expression pattern. This means the condition will only match if the value starts with e.g `Volume` in this case. But, in order to evaluate the condition as a regular expression, you'll want to use the `[[` construct instead of the old `[` test command, and use the `=~` operator to use regular expression matching.

There is a negation operation, prefixing the condition with an exclamation mark `!`. But I'm not sure if it works with a regular expression condition or not, if not I recommend you match all the things you want to exclude first, and use an empty body in the condition, i.e [a no-op operation](https://en.wikipedia.org/wiki/NOP_(code)) to do nothing with those. You can also add a fallback for all other cases in the form of an `else` block.

For a detailed reference of the `[[` expression and the differences with `[` here: https://mywiki.wooledge.org/BashFAQ/031

P.s.: if you have some example inputs (e.g. taken from `dunstctl history`), try and execute your file with these to see if it works as you intend it to:
```bash
DUNST_BODY="Not Volume" script.sh
# or
DUNST_BODY="Volume" script.sh
# etc...
```
